# MTK Hardware
BOARD_USES_MTK_HARDWARE := true
TARGET_USES_ION := true
BOARD_GLOBAL_CFLAGS += -DADD_LEGACY_ACQUIRE_BUFFER_SYMBOL
BOARD_GLOBAL_CFLAGS += -DMTK_HARDWARE

# LineageOS
BOARD_HARDWARE_CLASS := device/lenovo/p1m/lineagehw/

# Graphics
OVERRIDE_RS_DRIVER := libRSDriver_mtk.so
